GCC = gcc
FLAGS = -o
SOURCE = calculator.c add.c multiply.c subtraction.c division.c maximum.c power.c
calculator:
					 $(GCC) $(FLAGS) calculator $(SOURCE)
					 								 										  
clean:
			rm calculator.exe